latest devel and ver update
Signed-off-by: barakda <barak.davidov@gmail.com>

diff --git a/.github/workflows/build-container.yml b/.github/workflows/build-container.yml
--- a/.github/workflows/build-container.yml
+++ b/.github/workflows/build-container.yml
@@ -1,8 +1,6 @@
 ---
 # yamllint disable rule:line-length
 name: "CI"
-permissions:
-  contents: read
 on:  # yamllint disable rule:truthy
   push:
     tags:
@@ -11,9 +9,7 @@ on:  # yamllint disable rule:truthy
       - '*'
   pull_request:
     branches:
-      - devel
-  schedule:
-    - cron: '0 21 * * *'
+      - '*'
   workflow_dispatch:
   release:
     types:
@@ -107,7 +103,7 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        test: ["cli", "cli_change_lb", "cli_change_keys", "cli_change_ns_visibility", "cli_trash_rbd", "state", "multi_gateway", "server", "grpc", "omap_lock", "log_files", "nsid", "psk", "dhchap", "subsys_grp_name_append", "max_subsystems", "omap_no_read_lock", "omap_read_lock", "omap_read_lock_ignore_errors", "big_omap", "ns_limit", "cli_force_tls"]
+        test: ["cli", "cli_change_lb", "cli_change_keys", "cli_change_ns_visibility", "cli_trash_rbd", "state", "multi_gateway", "server", "grpc", "omap_lock", "log_files", "nsid", "psk", "dhchap", "subsys_grp_name_append", "max_subsystems", "omap_no_read_lock", "omap_read_lock", "omap_read_lock_ignore_errors", "big_omap", "ns_limit"]
     runs-on: ubuntu-latest
     env:
       HUGEPAGES: 512  # for multi gateway test, approx 256 per gateway instance
@@ -493,7 +489,7 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        test: ["sanity", "no_huge", "ns_lb_change", "no_subsystems", "auto_load_balance", "state_transitions", "state_transitions_both_gws", "state_transitions_loop", "state_transitions_rand_loop", "late_registration", "late_registration_loop", "connect_panic", "4gws", "4gws_loop", "4gws_create_delete", "4gws_create_delete_loop", "namespaces", "namespaces_loop", "mtls", "notify", "ceph_status", "blocklist", "main_exit", "listener_hostname", "cluster_pool", "flat_bdev_per_cluster", "set_qos", "set_qos_2ms", "rbd_qos", "auto_resize", "ns_read_only", "reuse_image", "image_shrink"]
+        test: ["sanity", "no_huge", "ns_lb_change", "no_subsystems", "auto_load_balance", "state_transitions", "state_transitions_both_gws", "state_transitions_loop", "state_transitions_rand_loop", "late_registration", "late_registration_loop", "4gws", "4gws_loop", "4gws_create_delete", "4gws_create_delete_loop", "namespaces", "namespaces_loop", "mtls", "notify", "ceph_status", "blocklist", "main_exit", "cluster_pool", "flat_bdev_per_cluster", "set_qos", "set_qos_2ms"]
     runs-on: ubuntu-latest
     env:
       HUGEPAGES: 1024  # 4 spdk instances
@@ -593,6 +589,12 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
+      # - name: Download container images
+      #   uses: actions/download-artifact@v4
+      #   with:
+      #     pattern: container_images_nvmeof
+      #     merge-multiple: true
+
       - name: Container_images_nvmeof folder (tar files) download
         run: |
           for i in {1..5}; do
@@ -609,7 +611,7 @@ jobs:
         run: |
           . .env
           ACTION_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
-          ./tests/atom/clusterBuildTestsRun.sh $NVMEOF_VERSION $CEPH_BRANCH $CEPH_SHA $ATOM_SHA $ACTION_URL 2>&1 | tee atom_nvmeof_console.log
+          ./tests/atom/clusterBuildTestsRun.sh $NVMEOF_VERSION $CEPH_BRANCH $CEPH_SHA $ATOM_SHA $ACTION_URL
 
       - name: Atom artifact build
         if: always()
@@ -623,184 +625,55 @@ jobs:
       #     name: atom-artifact
       #     path: /home/cephnvme/artifact_m7.tar.gz
 
-  # atom-nightly:
-  #   needs: [build, build-ceph]
-  #   if: github.repository == 'ceph/ceph-nvmeof' && github.event_name == 'schedule'
-  #   runs-on: nightlyAtomRunner
-  #   timeout-minutes: 1440
-  #   steps:
-  #     - name: Checkout code
-  #       uses: actions/checkout@v4
-
-  #     - name: Container_images_nvmeof folder (tar files) download
-  #       run: |
-  #         for i in {1..5}; do
-  #           echo "Attempt $i to download artifacts..."
-  #           gh run download --pattern "container_images_nvmeof" && break
-  #           echo "Download failed. Retrying in $((i * 5))s..."
-  #           sleep $((i * 5))
-  #         done
-  #       env:
-  #         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-            
-  #     - name: Cluster build and Atom nightly tests run
-  #       if: always()
-  #       run: |
-  #         . .env
-  #         ACTION_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
-  #         stdbuf -oL -eL ./tests/atom/clusterBuildTestsRun.sh $NVMEOF_VERSION $CEPH_BRANCH $CEPH_SHA $ATOM_SHA $ACTION_URL 'nightly' 2>&1 | tee atom_nightly_nvmeof_console.log
-  #         exit ${PIPESTATUS[0]}
-
-  #     - name: Atom artifact build nightly
-  #       if: always()
-  #       run: ./tests/atom/cpArtifactAndCleanup.sh 'nightly'
-
-  #     - name: Upload nightly nvmeof console as artifact
-  #       if: always()
-  #       uses: actions/upload-artifact@v4
-  #       with:
-  #         name: atom-nightly-nvmeof-full-console
-  #         path: atom_nightly_nvmeof_console.log
-
-  #     - name: Upload artifact for schedule events
-  #       uses: actions/upload-artifact@v4
-  #       if: always()
-  #       with:
-  #         name: atom-artifact
-  #         path: /home/cephnvme/artifact_m8.tar.gz
-
-  push-images-to-ceph-registry:
-    if: github.event_name == 'release'
-    needs: [pytest, demo, discovery, ha, atom]
-    runs-on: ubuntu-latest
-
+  atom-nightly:
+    needs: [build, build-ceph]
+    if: github.repository == 'ceph/ceph-nvmeof' && github.event_name == 'schedule'
+    runs-on: nightlyAtomRunner
+    timeout-minutes: 1440
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      - name: Download container images (nvmeof)
-        uses: actions/download-artifact@v4
-        with:
-          pattern: container_images_nvmeof*
-          merge-multiple: true
+      # - name: Download container images
+      #   uses: actions/download-artifact@v4
+      #   with:
+      #     pattern: container_images_nvmeof
+      #     merge-multiple: true
 
-      - name: Download container image (spdk)
-        uses: actions/download-artifact@v4
-        with:
-          pattern: container_image_spdk
-          merge-multiple: true
-
-      - name: Load container images
+      - name: Container_images_nvmeof folder (tar files) download
         run: |
-          docker load < nvmeof.tar
-          docker load < nvmeof-cli.tar
-          docker load < spdk.tar
+          for i in {1..5}; do
+            echo "Attempt $i to download artifacts..."
+            gh run download --pattern "container_images_nvmeof" && break
+            echo "Download failed. Retrying in $((i * 5))s..."
+            sleep $((i * 5))
+          done
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Login to quay.io
-        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772
-        with:
-          registry: ${{ vars.CONTAINER_REGISTRY }}
-          username: '${{ vars.CONTAINER_REGISTRY_USERNAME }}'
-          password: '${{ secrets.CONTAINER_REGISTRY_PASSWORD }}'
-
-      - name: Publish nvmeof containers and spdk when release/tag is created
-        run: |
-          make push
-
-  push-devel-image-to-ceph-registry:
-    if: github.event_name == 'push' && github.ref == 'refs/heads/devel'
-    needs: [pytest, demo, discovery, ha, atom]
-    runs-on: ubuntu-latest
-
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-
-      - name: Download container images
-        uses: actions/download-artifact@v4
-        with:
-          pattern: container_images_nvmeof*
-          merge-multiple: true
-
-      - name: Load container images
-        run: |
-          docker load < nvmeof.tar
-          docker load < nvmeof-cli.tar
-
-      - name: Login to quay.io
-        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772
-        with:
-          registry: ${{ vars.CONTAINER_REGISTRY }}
-          username: '${{ vars.CONTAINER_REGISTRY_USERNAME }}'
-          password: '${{ secrets.CONTAINER_REGISTRY_PASSWORD }}'
-
-      - name: Publish nvmeof containers when merged to devel
+      - name: Cluster build and Atom nightly tests run
+        if: always()
         run: |
           . .env
-          for image in nvmeof nvmeof-cli; do
-            docker tag $CONTAINER_REGISTRY/$image:$NVMEOF_VERSION $CONTAINER_REGISTRY/$image:devel
-            docker push $CONTAINER_REGISTRY/$image:devel
-          done
+          ACTION_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
+          stdbuf -oL -eL ./tests/atom/clusterBuildTestsRun.sh $NVMEOF_VERSION $CEPH_BRANCH $CEPH_SHA $ATOM_SHA $ACTION_URL 'nightly' 2>&1 | tee nightly_nvmeof_console.log
+          exit ${PIPESTATUS[0]}
 
-  pull-and-run-images:
-    needs: [push-images-to-ceph-registry]
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+      - name: Atom artifact build nightly
+        if: always()
+        run: ./tests/atom/cpArtifactAndCleanup.sh 'nightly'
 
-      - name: setup
-        run: make setup
+      # TODO: investigating upluad to artifact issue
+      # - name: Upload nightly nvmeof console as artifact
+      #   if: always()
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: nightly-nvmeof-full-console
+      #     path: nightly_nvmeof_console.log
 
-      - name: Pull Docker images from Quay.io
-        run: |
-          make pull || true  # Continue even if some images fail to pull
-
-      - name: List pulled images
-        run: docker images
-
-      - name: Verify downloaded images
-        run: |
-          . .env
-          REQUIRED_IMAGES=(
-            $QUAY_SPDK:$SPDK_VERSION
-            $QUAY_NVMEOFCLI:$NVMEOF_CLI_VERSION
-            $QUAY_NVMEOF:$NVMEOF_VERSION
-            $QUAY_CEPH:$CEPH_VERSION
-          )
-            
-          echo "Checking which required images are available:"
-          for image in "${REQUIRED_IMAGES[@]}"; do
-            if docker image inspect "$image" > /dev/null 2>&1; then
-              echo "✅ $image is available."
-            else
-              echo "❌ $image is missing."
-              exit 1  # Fail the job
-            fi
-          done
-
-      - name: Run Docker containers
-        run: make up
-
-      - name: Wait for the Gateway to be listening
-        timeout-minutes: 3
-        run: |
-          . .env
-
-          echo using gateway $NVMEOF_IP_ADDRESS port $NVMEOF_GW_PORT
-          until nc -z $NVMEOF_IP_ADDRESS $NVMEOF_GW_PORT; do
-            echo -n .
-            sleep ${{ env.WAIT_INTERVAL_SECS }}
-          done
-        
-      - name: check health
-        run: make ps
-
-      - name: Run demo
-        run: make demo
-      
-      - name: Tear down
-        if: success() || failure()
-        run: |
-          make down
-          make clean
+      # - name: Upload artifact for schedule events
+      #   uses: actions/upload-artifact@v4
+      #   if: always()
+      #   with:
+      #     name: atom-artifact
+      #     path: /home/cephnvme/artifact_m8.tar.gz
