Update build-container.yml (tentacle new branch)
fixing build-container.yml (tentacle new branch)

Signed-off-by: barakda <barak.davidov@gmail.com>

diff --git a/.github/workflows/build-container.yml b/.github/workflows/build-container.yml
--- a/.github/workflows/build-container.yml
+++ b/.github/workflows/build-container.yml
@@ -103,7 +103,7 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        test: ["cli", "cli_change_lb", "cli_change_keys", "cli_change_ns_visibility", "cli_trash_rbd", "state", "multi_gateway", "server", "grpc", "omap_lock", "log_files", "nsid", "psk", "dhchap", "subsys_grp_name_append", "max_subsystems", "omap_no_read_lock", "omap_read_lock", "omap_read_lock_ignore_errors", "big_omap", "ns_limit"]
+        test: ["cli", "cli_change_lb", "cli_change_keys", "cli_change_ns_visibility", "cli_trash_rbd", "state", "multi_gateway", "server", "grpc", "omap_lock", "log_files", "nsid", "psk", "dhchap", "subsys_grp_name_append", "max_subsystems", "omap_no_read_lock", "omap_read_lock", "omap_read_lock_ignore_errors", "big_omap", "ns_limit", "cli_force_tls"]
     runs-on: ubuntu-latest
     env:
       HUGEPAGES: 512  # for multi gateway test, approx 256 per gateway instance
@@ -489,7 +489,7 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        test: ["sanity", "no_huge", "ns_lb_change", "no_subsystems", "auto_load_balance", "state_transitions", "state_transitions_both_gws", "state_transitions_loop", "state_transitions_rand_loop", "late_registration", "late_registration_loop", "4gws", "4gws_loop", "4gws_create_delete", "4gws_create_delete_loop", "namespaces", "namespaces_loop", "mtls", "notify", "ceph_status", "blocklist", "main_exit", "cluster_pool", "flat_bdev_per_cluster", "set_qos", "set_qos_2ms"]
+        test: ["sanity", "no_huge", "ns_lb_change", "no_subsystems", "auto_load_balance", "state_transitions", "state_transitions_both_gws", "state_transitions_loop", "state_transitions_rand_loop", "late_registration", "late_registration_loop", "connect_panic", "4gws", "4gws_loop", "4gws_create_delete", "4gws_create_delete_loop", "namespaces", "namespaces_loop", "mtls", "notify", "ceph_status", "blocklist", "main_exit", "listener_hostname", "cluster_pool", "flat_bdev_per_cluster", "set_qos", "set_qos_2ms", "rbd_qos", "auto_resize", "ns_read_only", "reuse_image", "image_shrink"]
     runs-on: ubuntu-latest
     env:
       HUGEPAGES: 1024  # 4 spdk instances
@@ -611,7 +611,7 @@ jobs:
         run: |
           . .env
           ACTION_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
-          ./tests/atom/clusterBuildTestsRun.sh $NVMEOF_VERSION $CEPH_BRANCH $CEPH_SHA $ATOM_SHA $ACTION_URL
+          ./tests/atom/clusterBuildTestsRun.sh $NVMEOF_VERSION $CEPH_BRANCH $CEPH_SHA $ATOM_SHA $ACTION_URL 2>&1 | tee atom_nvmeof_console.log
 
       - name: Atom artifact build
         if: always()
@@ -625,55 +625,48 @@ jobs:
       #     name: atom-artifact
       #     path: /home/cephnvme/artifact_m7.tar.gz
 
-  atom-nightly:
-    needs: [build, build-ceph]
-    if: github.repository == 'ceph/ceph-nvmeof' && github.event_name == 'schedule'
-    runs-on: nightlyAtomRunner
-    timeout-minutes: 1440
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+  # atom-nightly:
+  #   needs: [build, build-ceph]
+  #   if: github.repository == 'ceph/ceph-nvmeof' && github.event_name == 'schedule'
+  #   runs-on: nightlyAtomRunner
+  #   timeout-minutes: 1440
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
 
-      # - name: Download container images
-      #   uses: actions/download-artifact@v4
-      #   with:
-      #     pattern: container_images_nvmeof
-      #     merge-multiple: true
+  #     - name: Container_images_nvmeof folder (tar files) download
+  #       run: |
+  #         for i in {1..5}; do
+  #           echo "Attempt $i to download artifacts..."
+  #           gh run download --pattern "container_images_nvmeof" && break
+  #           echo "Download failed. Retrying in $((i * 5))s..."
+  #           sleep $((i * 5))
+  #         done
+  #       env:
+  #         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+            
+  #     - name: Cluster build and Atom nightly tests run
+  #       if: always()
+  #       run: |
+  #         . .env
+  #         ACTION_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
+  #         stdbuf -oL -eL ./tests/atom/clusterBuildTestsRun.sh $NVMEOF_VERSION $CEPH_BRANCH $CEPH_SHA $ATOM_SHA $ACTION_URL 'nightly' 2>&1 | tee atom_nightly_nvmeof_console.log
+  #         exit ${PIPESTATUS[0]}
 
-      - name: Container_images_nvmeof folder (tar files) download
-        run: |
-          for i in {1..5}; do
-            echo "Attempt $i to download artifacts..."
-            gh run download --pattern "container_images_nvmeof" && break
-            echo "Download failed. Retrying in $((i * 5))s..."
-            sleep $((i * 5))
-          done
-        env:
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #     - name: Atom artifact build nightly
+  #       if: always()
+  #       run: ./tests/atom/cpArtifactAndCleanup.sh 'nightly'
 
-      - name: Cluster build and Atom nightly tests run
-        if: always()
-        run: |
-          . .env
-          ACTION_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
-          stdbuf -oL -eL ./tests/atom/clusterBuildTestsRun.sh $NVMEOF_VERSION $CEPH_BRANCH $CEPH_SHA $ATOM_SHA $ACTION_URL 'nightly' 2>&1 | tee nightly_nvmeof_console.log
-          exit ${PIPESTATUS[0]}
+  #     - name: Upload nightly nvmeof console as artifact
+  #       if: always()
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: atom-nightly-nvmeof-full-console
+  #         path: atom_nightly_nvmeof_console.log
 
-      - name: Atom artifact build nightly
-        if: always()
-        run: ./tests/atom/cpArtifactAndCleanup.sh 'nightly'
-
-      # TODO: investigating upluad to artifact issue
-      # - name: Upload nightly nvmeof console as artifact
-      #   if: always()
-      #   uses: actions/upload-artifact@v4
-      #   with:
-      #     name: nightly-nvmeof-full-console
-      #     path: nightly_nvmeof_console.log
-
-      # - name: Upload artifact for schedule events
-      #   uses: actions/upload-artifact@v4
-      #   if: always()
-      #   with:
-      #     name: atom-artifact
-      #     path: /home/cephnvme/artifact_m8.tar.gz
+  #     - name: Upload artifact for schedule events
+  #       uses: actions/upload-artifact@v4
+  #       if: always()
+  #       with:
+  #         name: atom-artifact
+  #         path: /home/cephnvme/artifact_m8.tar.gz
