atom_tests_add
Signed-off-by: barakda <barak.davidov@gmail.com>

diff --git a/.github/workflows/build-container.yml b/.github/workflows/build-container.yml
--- a/.github/workflows/build-container.yml
+++ b/.github/workflows/build-container.yml
@@ -23,47 +23,47 @@ concurrency:
 env:
   WAIT_INTERVAL_SECS: 1
 jobs:
-  build:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-        with:
-          submodules: recursive
+  # build:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
+  #       with:
+  #         submodules: recursive
 
-      - name: Build container images - spdk
-        run: make build SVC="spdk" SPDK_TARGET_ARCH=x86-64-v2
+  #     - name: Build container images - spdk
+  #       run: make build SVC="spdk" SPDK_TARGET_ARCH=x86-64-v2
 
-      - name: Build container images - bdevperf
-        run: make build SVC="bdevperf" SPDK_TARGET_ARCH=x86-64-v2
+  #     - name: Build container images - bdevperf
+  #       run: make build SVC="bdevperf" SPDK_TARGET_ARCH=x86-64-v2
 
-      - name: Build container images - nvmeof
-        run: make build SVC="nvmeof" SPDK_TARGET_ARCH=x86-64-v2
+  #     - name: Build container images - nvmeof
+  #       run: make build SVC="nvmeof" SPDK_TARGET_ARCH=x86-64-v2
 
-      - name: Build container images - nvmeof-cli
-        run: make build SVC="nvmeof-cli" SPDK_TARGET_ARCH=x86-64-v2
+  #     - name: Build container images - nvmeof-cli
+  #       run: make build SVC="nvmeof-cli" SPDK_TARGET_ARCH=x86-64-v2
 
-      - name: Save container images
-        run: |
-          . .env
-          docker save $QUAY_NVMEOF:$NVMEOF_VERSION > nvmeof.tar
-          docker save $QUAY_NVMEOFCLI:$NVMEOF_VERSION > nvmeof-cli.tar
-          docker save bdevperf > bdevperf.tar
+  #     - name: Save container images
+  #       run: |
+  #         . .env
+  #         docker save $QUAY_NVMEOF:$NVMEOF_VERSION > nvmeof.tar
+  #         docker save $QUAY_NVMEOFCLI:$NVMEOF_VERSION > nvmeof-cli.tar
+  #         docker save bdevperf > bdevperf.tar
 
-      - name: Upload bdevperf container image
-        uses: actions/upload-artifact@v4
-        with:
-          name: container_images_bdevperf
-          path: |
-            bdevperf.tar
+  #     - name: Upload bdevperf container image
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: container_images_bdevperf
+  #         path: |
+  #           bdevperf.tar
 
-      - name: Upload nvmeof container images
-        uses: actions/upload-artifact@v4
-        with:
-          name: container_images_nvmeof
-          path: |
-            nvmeof.tar
-            nvmeof-cli.tar
+  #     - name: Upload nvmeof container images
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: container_images_nvmeof
+  #         path: |
+  #           nvmeof.tar
+  #           nvmeof-cli.tar
 
   # build-ceph:
   #   runs-on: ubuntu-latest
@@ -653,9 +653,9 @@ jobs:
 
   atom:
     # needs: [build, build-ceph]
-    needs: [build]
+    # needs: [build]
     # if: github.repository_owner == 'devel'
-    if: github.repository == 'ceph/ceph-nvmeof'
+    # if: github.repository == 'ceph/ceph-nvmeof'
     runs-on: ibmcloud-1
     steps:
       - name: Checkout code
@@ -665,11 +665,11 @@ jobs:
         run: |
           . .env
           set -x
+          echo ${{ github.repository_owner }}
+          echo ${{ github.repository }}
           echo "_1_ATOM_BRANCH : $ATOM_BRANCH"
           echo "_1_ATOM_SHA : $ATOM_SHA"
-          echo chmod +x ./tests/atom/atomEnvInit.sh
-          echo ./tests/atom/atomEnvInit.sh ${{ vars.CONTAINER_PRIVATE_REGISTRY_USERNAME }} ${{ github.repository_owner }} ${{ secrets.ATOM_REPO_TOKEN }} $ATOM_BRANCH $ATOM_SHA
-# ./tests/atom/atomEnvInit.sh ${{ vars.CONTAINER_PRIVATE_REGISTRY_USERNAME }} ${{ github.repository_owner }} ${{ secrets.ATOM_REPO_TOKEN }} $ATOM_BRANCH $ATOM_SHA
+          ./tests/atom/atomEnvInit.sh $ATOM_BRANCH $ATOM_SHA ${{ vars.CONTAINER_PRIVATE_REGISTRY_USERNAME }} ${{ github.repository_owner }} ${{ secrets.ATOM_REPO_TOKEN }}
 
       - name: Download container images
         uses: actions/download-artifact@v4
@@ -677,26 +677,26 @@ jobs:
           pattern: container_images_nvmeof
           merge-multiple: true
 
-      - name: Load container images
-        run: |
-          docker load < nvmeof.tar
-          docker load < nvmeof-cli.tar
+      # - name: Load container images
+      #   run: |
+      #     docker load < nvmeof.tar
+      #     docker load < nvmeof-cli.tar
 
-      - name: Cluster build and Atom tests run
-        if: always() || failure()
-        run: |
-          . .env
-          ./tests/atom/atomClusterBuildTestsRun.sh $GITHUB_REPOSITORY ${GITHUB_REF##*/} $NVMEOF_VERSION $CEPH_SHA $ATOM_SHA
+      # - name: Cluster build and Atom tests run
+      #   if: always() || failure()
+      #   run: |
+      #     . .env
+      #     ./tests/atom/atomClusterBuildTestsRun.sh $GITHUB_REPOSITORY ${GITHUB_REF##*/} $NVMEOF_VERSION $CEPH_SHA $ATOM_SHA
 
-      - name: Atom artifact build
-        if: always()
-        run: ./tests/atom/cpArtifactAndCleanup.sh
+      # - name: Atom artifact build
+      #   if: always()
+      #   run: ./tests/atom/cpArtifactAndCleanup.sh
 
-      - uses: actions/upload-artifact@v4
-        if: always()
-        with:
-          name: atom-artifact
-          path: /tmp/artifact/*
+      # - uses: actions/upload-artifact@v4
+      #   if: always()
+      #   with:
+      #     name: atom-artifact
+      #     path: /tmp/artifact/*
 
   # push-images-to-private-registry:
   #   if: github.event_name == 'push' && github.ref == 'refs/heads/devel' && github.repository == 'ceph/ceph-nvmeof'
